// 改变模式
export const SET_MODEL = 'SET_MODEL'
// loading
export const SET_LOADING = 'SET_LOADING'
// 发现页
export const SET_FIND_RECOMMEND_LIST = 'SET_FIND_RECOMMEND_LIST'
export const SET_FIND_SWIPERS = 'SET_FIND_SWIPERS'
export const SET_FIND_TABLIST = 'SET_FIND_TABLIST'
export const ADD_FIND_RECOMMEND_LIST = 'ADD_FIND_RECOMMEND_LIST'
export const SET_LIKE = 'SET_LIKE'
// 搜索页
export const SET_SEARCH_SWIPER = 'SET_SEARCH_SWIPER'
export const SET_SEARCH_HOTKEY = 'SET_SEARCH_HOTKEY'
export const SET_SEARCH_SUGGEST = 'SET_SEARCH_SUGGEST'
export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY'
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'
// 自定义导航列表页
export const SET_CHANGE_LIST = 'SET_CHANGE_LIST'